# Keys for LocalizationManger to use in source code: MIT License
# @author Vladimir Petrenko
@tool
class_name LocalizationKeys

const PROGRAM_TITLE = "PROGRAM_TITLE"
const SONG_TITLE = "SONG_TITLE"
const SONG_TITLE_SEARCHABLE = "SONG_TITLE_SEARCHABLE"
const SONG_ARTIST = "SONG_ARTIST"
const SONG_ARTIST_SEARCHABLE = "SONG_ARTIST_SEARCHABLE"
const SONG_LYRIC = "SONG_LYRIC"
const SONG_GENRE = "SONG_GENRE"
const SONG_GENRE_SEARCHABLE = "SONG_GENRE_SEARCHABLE"
const SONG_REMARKS = "SONG_REMARKS"
const SONG_LINK = "SONG_LINK"
const BTN_SAVE = "BTN_SAVE"
const BTN_UPDATE = "BTN_UPDATE"
const BTN_CANCEL = "BTN_CANCEL"
const BTN_DELETE = "BTN_DELETE"
const BTN_ADD_SONG = "BTN_ADD_SONG"

const KEYS = [
 "PROGRAM_TITLE",
 "SONG_TITLE",
 "SONG_TITLE_SEARCHABLE",
 "SONG_ARTIST",
 "SONG_ARTIST_SEARCHABLE",
 "SONG_LYRIC",
 "SONG_GENRE",
 "SONG_GENRE_SEARCHABLE",
 "SONG_REMARKS",
 "SONG_LINK",
 "BTN_SAVE",
 "BTN_UPDATE",
 "BTN_CANCEL",
 "BTN_DELETE",
 "BTN_ADD_SONG"
]